# -*- coding: utf-8 -*-
{
    "name": "La Leona | POS Multimoneda PRO",
    "version": "18.0.2.3.0",
    "summary": "Precios nativos USD/CRC, BCCR, cobros físicos, vuelto seleccionable y cierres multimoneda.",
    "category": "Point of Sale",
    "author": "Castro Li",
    "website": "https://castrolicr.com",
    "license": "LGPL-3",
    "depends": [
        "point_of_sale",
        "sale",
        "stock",
        "account",
        "l10n_cr_currency_rate_live",
        "l10n_cr_invoice_pos",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/product_template_views.xml",
        "views/pos_payment_method_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/pos_session_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_multicurrency/static/src/js/multicurrency_models.js",
            "pos_multicurrency/static/src/js/sale_order_multicurrency.js",
            "pos_multicurrency/static/src/js/order_summary_multicurrency.js",
            "pos_multicurrency/static/src/js/payment_screen.js",
            "pos_multicurrency/static/src/js/cash_controls.js",
            "pos_multicurrency/static/src/js/receipt_multicurrency.js",
            "pos_multicurrency/static/src/xml/order_summary_multicurrency.xml",
            "pos_multicurrency/static/src/xml/payment_screen.xml",
            "pos_multicurrency/static/src/xml/cash_controls.xml",
            "pos_multicurrency/static/src/xml/receipt_multicurrency.xml",
            "pos_multicurrency/static/src/scss/multicurrency.scss",
        ],
    },
    "installable": True,
    "application": False,
}
